# Generated by Django 3.0.8 on 2020-07-28 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
