# Generated by Django 3.0.8 on 2020-07-29 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200729_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.Listing'),
        ),
    ]
