# Generated by Django 3.0.8 on 2020-07-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200729_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='item_catagory',
            field=models.CharField(default='electronic', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='item_description',
            field=models.TextField(default='Good product'),
        ),
    ]
