# Generated by Django 3.0.8 on 2020-07-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200730_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_price',
            field=models.FloatField(),
        ),
    ]
