# Generated by Django 3.0.8 on 2020-07-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200730_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='item_description',
            field=models.TextField(default=False),
        ),
    ]
